### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-dotnet#66]
```java
 [Plugin: org.mustbe.consulo.csharp]:  [Plugin: org.mustbe.consulo.csharp]
com.intellij.diagnostic.PluginException:  [Plugin: org.mustbe.consulo.csharp]
	at com.intellij.compiler.impl.CompileDriver.doCompile(CompileDriver.java:570)
	at com.intellij.compiler.impl.CompileDriver.access$700(CompileDriver.java:103)
	at com.intellij.compiler.impl.CompileDriver$6.run(CompileDriver.java:499)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:624)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$4.run(ProgressManagerImpl.java:199)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:288)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:238)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:186)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$10.run(ProgressManagerImpl.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:407)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:51)
Caused by: java.lang.AssertionError
	at org.mustbe.consulo.microsoft.csharp.module.extension.MicrosoftCSharpModuleExtension.createCompilerOptionsBuilder(MicrosoftCSharpModuleExtension.java:58)
	at org.mustbe.consulo.dotnet.compiler.DotNetCompiler.compile(DotNetCompiler.java:120)
	at com.intellij.compiler.impl.CompileDriver.compileSources(CompileDriver.java:1840)
	at com.intellij.compiler.impl.CompileDriver.translate(CompileDriver.java:1153)
	at com.intellij.compiler.impl.CompileDriver.doCompile(CompileDriver.java:850)
	at com.intellij.compiler.impl.CompileDriver.doCompile(CompileDriver.java:551)
	... 16 more

```

**Comment by VISTALL** [comment]
Fixed by https://github.com/consulo/consulo-csharp/commit/4466d2118acd27032b92e5b647d56f548e77e9a9
