### ISSUE TITLE
Debbuger Variables with showing Collecting data... no other data

### ISSUE THREAD

**Issue by winalex** [consulo/consulo-dotnet#75]
stops of break point no data in Variables and throw this exception `null
java.lang.UnsupportedOperationException
	at mono.debugger.JDWPException.asUncheckedException(JDWPException.java:60)
	at mono.debugger.CustomAttributeMirrorOwner.customAttributes(CustomAttributeMirrorOwner.java:63)
	at consulo.dotnet.mono.debugger.proxy.MonoMethodProxy.isAnnotatedBy(MonoMethodProxy.java:70)
	at consulo.dotnet.debugger.nodes.DotNetThisAsObjectValueNode.isHiddenPropertyOrField(DotNetThisAsObjectValueNode.java:185)
	at consulo.dotnet.debugger.nodes.DotNetThisAsObjectValueNode.processFieldOrProperty(DotNetThisAsObjectValueNode.java:161)
	at consulo.dotnet.debugger.nodes.DotNetThisAsObjectValueNode.computeChildren(DotNetThisAsObjectValueNode.java:137)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.startComputingChildren(XValueContainerNode.java:65)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.loadChildren(XValueContainerNode.java:59)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.getChildren(XValueContainerNode.java:237)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode$1.run(XValueContainerNode.java:105)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:82)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:79)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:98)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:36)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)`

**Comment by VISTALL** [comment]
Unexpected error from Unity side.They have so old mono debugger version. Looks like property duplication need fix by another way.

**Comment by winalex** [comment]
I'm using with Unity 5.4b17 and MonoDevelop is 5.9.6. think they moved to new mono but old debugger?

**Comment by VISTALL** [comment]
Maybe i wrong - but for now unity didn't update mono core. For now they use **mono 2.0** and debugger version **2.1**

**Comment by VISTALL** [comment]
Fixed. Sorry

**Comment by VISTALL** [comment]
Btw - current mono debugger version is **2.42**
