### ISSUE TITLE
Debugger freezing on step over

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-dotnet#90]
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on mono.debugger.Packet@2994bf87
	at java.base@11.0.4/java.lang.Object.wait(Native Method)
	at java.base@11.0.4/java.lang.Object.wait(Object.java:328)
	at consulo.dotnet.mono//mono.debugger.TargetVM.waitForReply(TargetVM.java:350)
	at consulo.dotnet.mono//mono.debugger.VirtualMachineImpl.waitForTargetReply(VirtualMachineImpl.java:457)
	at consulo.dotnet.mono//mono.debugger.PacketStream.waitForReply(PacketStream.java:84)
	at consulo.dotnet.mono//mono.debugger.protocol.VirtualMachine_InvokeMethod.waitForReply(VirtualMachine_InvokeMethod.java:46)
	at consulo.dotnet.mono//mono.debugger.protocol.VirtualMachine_InvokeMethod.process(VirtualMachine_InvokeMethod.java:24)
	at consulo.dotnet.mono//mono.debugger.MethodMirror.invokeNew(MethodMirror.java:140)
	at consulo.dotnet.mono//consulo.dotnet.mono.debugger.proxy.MonoMethodProxy.invokeAdvanced(MonoMethodProxy.java:140)
	at consulo.dotnet.mono//consulo.dotnet.mono.debugger.proxy.MonoMethodProxy.invoke(MonoMethodProxy.java:120)
	at consulo.csharp//consulo.csharp.ide.debugger.expressionEvaluator.PropertyEvaluator.invoke(PropertyEvaluator.java:59)
	at consulo.csharp//consulo.csharp.ide.debugger.expressionEvaluator.PropertyEvaluator.invoke(PropertyEvaluator.java:35)
	at consulo.csharp//consulo.csharp.ide.debugger.expressionEvaluator.FieldOrPropertyEvaluator.invokeFieldOrProperty(FieldOrPropertyEvaluator.java:160)
	at consulo.csharp//consulo.csharp.ide.debugger.expressionEvaluator.FieldOrPropertyEvaluator.evaluate(FieldOrPropertyEvaluator.java:118)
	at consulo.csharp//consulo.csharp.ide.debugger.CSharpEvaluateContext.evaluate(CSharpEvaluateContext.java:93)
	at consulo.csharp//consulo.csharp.ide.debugger.CSharpDebuggerProvider.evaluate(CSharpDebuggerProvider.java:146)
	at consulo.dotnet//consulo.dotnet.debugger.DotNetDebuggerEvaluator.evaluate(DotNetDebuggerEvaluator.java:82)
	at com.intellij//com.intellij.xdebugger.impl.ui.tree.nodes.WatchNodeImpl$XWatchValue.computePresentation(WatchNodeImpl.java:94)
	at com.intellij//com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:72)
	at com.intellij//com.intellij.xdebugger.impl.ui.tree.nodes.WatchNodeImpl.<init>(WatchNodeImpl.java:44)
	at com.intellij//com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.<init>(WatchesRootNode.java:71)
	at com.intellij//com.intellij.xdebugger.impl.frame.XWatchesViewImpl.createNewRootNode(XWatchesViewImpl.java:243)
	at com.intellij//com.intellij.xdebugger.impl.frame.XVariablesViewBase.buildTreeAndRestoreState(XVariablesViewBase.java:80)
	at com.intellij//com.intellij.xdebugger.impl.frame.XVariablesView.lambda$processSessionEvent$0(XVariablesView.java:85)
	at com.intellij//com.intellij.xdebugger.impl.frame.XVariablesView$$Lambda$3274/0x0000000801f8c040.run(Unknown Source)
	at consulo.platform.desktop//com.intellij.openapi.application.DesktopTransactionGuardImpl$2.run(DesktopTransactionGuardImpl.java:321)
	at com.intellij//consulo.application.impl.BaseApplication.runIntendedWriteActionOnCurrentThread(BaseApplication.java:792)
	at consulo.platform.desktop//com.intellij.openapi.application.impl.DesktopApplicationImpl.lambda$invokeLater$9(DesktopApplicationImpl.java:248)
	at consulo.platform.desktop//com.intellij.openapi.application.impl.DesktopApplicationImpl$$Lambda$633/0x00000008007e4c40.run(Unknown Source)
	at com.intellij//com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:88)
	at com.intellij//com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:137)
	at com.intellij//com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:50)
	at com.intellij//com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:193)
	at java.desktop@11.0.4/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.4/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.4/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.4/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.4/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.4/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.4/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij//com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:848)
	at com.intellij//com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:759)
	at com.intellij//com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:421)
	at com.intellij//com.intellij.ide.IdeEventQueue$$Lambda$898/0x0000000800c28c40.compute(Unknown Source)
	at com.intellij//com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:722)
	at com.intellij//com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:420)
	at com.intellij//com.intellij.ide.IdeEventQueue$$Lambda$897/0x0000000800c29c40.run(Unknown Source)
	at com.intellij//consulo.application.impl.BaseApplication.runIntendedWriteActionOnCurrentThread(BaseApplication.java:792)
	at com.intellij//com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:463)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.4/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by VISTALL** [comment]
duplicate https://github.com/consulo/consulo-csharp/issues/579
